- name: Load Named snapshot
  hosts: fw1 
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  vars:
    named_snapshot: Sunbelt_Rev10.xml
    ansible_python_interpreter: /home/ansible/ansible/bin/python    
  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'no'

  - name: wait for SSH (timeout 10min)
    wait_for: port=22 host='fw1' search_regex=SSH timeout=600

  - name: checking if device ready
    panos_check:
      ip_address: "{{ ip_address }}"
      password: "{{ password }}"
    register: result
    until: not result|failed
    retries: 10
    delay: 10

  - name: import config
    panos_import:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      file: '{{ named_snapshot }}'
      category: 'configuration'
    register: result

  - name: Load already imported named configuration
    panos_loadcfg:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
      file: "{{ result.filename }}"
      commit: False

  - name: commit (blocks until finished)
    panos_commit:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
